### ISSUE TITLE
Vault binary update

### ISSUE THREAD

**Issue by den-is** [jsok/puppet-vault#84] opened 2017-08-17 11:45 UTC
Install doesn't update vault when you update version.
Maybe it's ok to remove this check
https://github.com/jsok/puppet-vault/blob/master/manifests/install.pp#L20

Or add some parameter to module like `allow_update`

**Comment by jsok** [comment] 2017-08-17 11:53
Duplicate of #63

**Closed by jsok** 2017-08-17 11:53 UTC
